### ISSUE TITLE
Issues to fix:

### ISSUE THREAD

**Issue by MilaBar** [ExLibrisGroup/Cloud-App-Change-RS-Requests#11]
1.	“Convert Article to a Book” - the setting shows “Article\Chapter title -> Chapter number”, but the “Journal Title” is transferred to a “Chapter number” field. Please fix.
2.	The App should transfer the Request Attributes to a new request type without any changes. However, when the App transferred a request for a digital item to a new type, it removed a requester's email address from Alternative Address and placed it to Email address.

**Comment by ori229** [comment]
1. Fixed: https://github.com/ExLibrisGroup/Cloud-App-Change-RS-Requests/commit/fa0fc969a0290d9bb6d2432bbdcd7d44bda1fd30 
2. This is on Alma's side. We'll fix it for Nov 2022 Release

**Comment by libdevhub** [comment]
1.	After a patron submits a request, they get a confirmation letter (as expected).
However, when we use the Cloud App to change the Request Type, the patron gets another confirmation letter
2.	If a patron fills in the incorrect format, such as Physical, instead of Digital, but everything else is correct, the confirmation letter displays the Article Title that already appears as the Journal Title

**Comment by ori229** [comment]
MilaBar, Now that Nov release is installed, can you verify that it works well?

**Comment by MilaBar** [comment]
Hi ori229,

Yes, this issue (App changing the Request Attributes) is fixed now. Thank you.
However, I have noticed that different confirmation messages are displayed when transferring is successful (see attached). It is very useful to see a new request status. Can we have the only message which shows the status please?

Thank you 
[App_ confirmation messages.docx](https://github.com/ExLibrisGroup/Cloud-App-Change-RS-Requests/files/9960304/App_.confirmation.messages.docx)

**Comment by ori229** [comment]
Apologies for not replying earlier...
The request status is not updated immediately after the Cloud-App sends the API request, since Alma runs a process in the background. Therefor the Cloud App can't show it - you'll need to check the status in Alma's UI.

**Comment by MilaBar** [comment]
Hi ori229. Yes, I have got it now. I use your App almost daily. Thank you for creating it 👍. Kind regards, Mila
