### ISSUE TITLE
An additional parameter to add

### ISSUE THREAD

**Issue by MilaBar** [ExLibrisGroup/Cloud-App-Change-RS-Requests#12]
Please add a parameter “Chapter number -> Article\Chapter title” to “Convert Book to an Article” type.

**Comment by ori229** [comment]
Done: https://github.com/ExLibrisGroup/Cloud-App-Change-RS-Requests/commit/fa0fc969a0290d9bb6d2432bbdcd7d44bda1fd30

**Comment by MilaBar** [comment]
It has not been done. I cannot see this parameter in the App settings for “Convert Book to an Article”:
![“Convert Book to an Article”](https://user-images.githubusercontent.com/111980087/192782733-c84a5a3b-e997-4cd0-a928-67c2613586fd.jpg)

**Comment by YehuditAdler** [comment]
@MilaBar, may I ask you to try and "Reset" the settings?

**Comment by MilaBar** [comment]
Dear Yehudit,

Thank you for your message. I have just reset the settings and get the parameter I need.
Thank you very much!

Kind regards,
Mila
