### ISSUE TITLE
Additional questions to clarify

### ISSUE THREAD

**Issue by MilaBar** [ExLibrisGroup/Cloud-App-Change-RS-Requests#13]
When an option “Delete old requests after creating the new one” is selected, the original request should be deleted regardless of the partner assigned to the request. It works but not for requests assigned to the RapidILL. The message "The Partner does not support cancel workflow step". What is a reason for keeping two Active requests for the same item assigned to the same partner in Alma? Obviously, the library staff should remember to cancel/delete the original request manually. 
Are there any other partners included to this exception?

**Comment by ori229** [comment]
We'll add a comment about it to the doc.

**Comment by ori229** [comment]
Added: https://developers.exlibrisgroup.com/appcenter/change-rs-requests-type/

**Comment by MilaBar** [comment]
Sorry, I have not got this. What does it mean "We'll add a comment about it to the doc."? Will original requests assigned to the RapidILL be deleted after successful transferring to a new request type?

**Comment by ori229** [comment]
Here is what we added to the doc:

> The app creates a new request and afterwards cancels the old one. The partners’ workflow profile should therefore allow “cancel by staff”.
> Note: for RapidILL, the ‘Configure RapidILL as a Resource Sharing Partner’ page mentions: ‘To allow cancelling by staff from Alma, make sure the workflow profile has the “Cancelled by staff” action checked.’.

Does that help?
