### ISSUE TITLE
Article to Book chapter - stopped working - urgent!

### ISSUE THREAD

**Issue by MilaBar** [ExLibrisGroup/Cloud-App-Change-RS-Requests#14]
The App has suddenly stopped working today: the Aricle/ChapterTitle stopped being transferred to a ChapterNumber. 
Please see my screenshots attached.  Could you please fix it asap.

![Article to Book settings](https://user-images.githubusercontent.com/111980087/203341663-82bf2e56-1160-48f5-9d50-e76b4ac06c16.jpg)
![Transferring result](https://user-images.githubusercontent.com/111980087/203341744-71cbe6be-6e22-43d4-871a-0e075869d7af.jpg)
![Request in Alma](https://user-images.githubusercontent.com/111980087/203341773-75c29c33-ae2e-4a5e-96a8-4c6093cdb9a5.jpg)

**Comment by ori229** [comment]
The Cloud App was modified for 3 months (and also Alma Nov Release is on prod for 3 weeks), so it's not likely to be a bug which suddenly appeared. Perhaps you changed the Cloud App's configuration? I see above that "Artice\Chapter title" is configured to be written to both "Chapter title" and "Chapter number". Do you need it in both? Perhaps you can change the configuration to have it written only to "Chapter number" and see if that helps.

**Comment by MilaBar** [comment]
It did work well previously for transferring "Article\Chapter title" to both "Chapter title" and "Chapter number". I have removed " Article \Chapter title" to "Chapter title” and left only " Article \Chapter title" to "Chapter number" but it does not make it to appear in "Chapter number". You can clearly see that the App does not mention transferring " Article \Chapter title" to "Chapter number" in the green confirmation message. See the test result below:

![Settings_2](https://user-images.githubusercontent.com/111980087/203356508-d66c613d-484a-463b-a351-ea50b0002b60.jpg)
![Result_2](https://user-images.githubusercontent.com/111980087/203356542-fdcc5330-9840-4807-8e8e-2450cb9b2477.jpg)
![Request in Alma_2](https://user-images.githubusercontent.com/111980087/203356677-45cbc7f8-442b-4bc3-9c01-930386a50376.jpg)

Any further suggestions?

**Comment by ori229** [comment]
Your configuration also has "Chapter -> Chapter number"  so this checkbox is preferred over "Article\Chapter title -> Chapter number".  Can you try to uncheck that?
(You can return "Article\Chapter title -> Title")

**Comment by MilaBar** [comment]
That's it! "Chapter -> Chapter number" overwrites "Article\Chapter title -> Chapter number". I have unticked it and got "Article\Chapter title -> Chapter number" working now!
![Settings_3](https://user-images.githubusercontent.com/111980087/203371385-e50e6ff5-978e-4638-b709-6ea310312d75.jpg)
![Result _ 3](https://user-images.githubusercontent.com/111980087/203371437-4fb766c2-f65f-4381-9a0d-42a36111495c.jpg)

Thank you so much for helping me to sort this all out! Please mark this issue as resolved.
