### ISSUE TITLE
The application does not work

### ISSUE THREAD

**Issue by Yul279** [ExLibrisGroup/Cloud-App-Change-RS-Requests#2]
Hi,
The application does not work in our environment (Tel-Aviv University). 
We have the following configuration in Alma:
5 libraries in one institution
1RS library and 4 RS-Desks
Do you support this configuration?
Thanks,
Yulia

**Comment by YehuditAdler** [comment]
Hi Julia,
In theory, your configuration should work.
It is difficult to know what’s wrong without some screenshots. 
Can you send a screenshot of the whole browser to me by email?
Thanks,
Yehudit
Yehudit.Adler@exlibrisgroup.com

**Comment by afdawson** [comment]
Hi Yehudit, 

Tried this out this morning, and got this issue:
![screenshot2](https://user-images.githubusercontent.com/38752719/109287883-13b55380-781c-11eb-89df-a6d8a7b37f82.PNG)

Let me know if you want me to do anything / try anything?

Alan

**Comment by YehuditAdler** [comment]
Hi Alan,

Please try setting a value in the "Language" drop-down. 
This seems like a bug, which we will try to address ASAP, but in the meantime, you’ll need to set the language before using the Cloud App.

Yehudit,

**Comment by ori229** [comment]
It will be fixed with Alma's May release (internal code: URM-148186)

**Comment by ori229** [comment]
May Release installed
