### ISSUE TITLE
Cloud App won't change the request type

### ISSUE THREAD

**Issue by Kirrarne** [ExLibrisGroup/Cloud-App-Change-RS-Requests#3]
We are trying to change a request for a chapter from a book that has come in on the book form and change it to the copy form.  Request has the details of the book, author, chapter, pages however we keep getting an error that says it can't do that:

![image](https://user-images.githubusercontent.com/81335158/112396597-88fd4100-8d54-11eb-9b67-fa5ed0243b99.png)

2 examples also attached.  

Does the Cloud App change the form in this way?  If not, is there anywhere we can find more information on what this app actually does as we have been unsuccessful in using it to change forms for any requests.

Thanks!  :)
[Cloud App - RS form change.docx](https://github.com/ExLibrisGroup/Cloud-App-Change-RS-Requests/files/6201026/Cloud.App.-.RS.form.change.docx)

**Comment by ori229** [comment]
Please try changing the App’s configuration by switching these 2:
![image](https://user-images.githubusercontent.com/139582/112833482-78740000-909f-11eb-989a-4e66d9a4882c.png)

**Comment by Kirrarne** [comment]
Hi,

Thanks, have changed that but now seem to be getting this error - previously been reported so assuming the bug is still there?

![image](https://user-images.githubusercontent.com/81335158/112900802-ab65d480-912f-11eb-8ee0-92c25bacb6ea.png)


Good to know that we can change the configs, will try a few other things to see if it will change it.

Thanks,
Kirrarne

**Comment by Kirrarne** [comment]
Sorry, closed by mistake.

**Comment by Kirrarne** [comment]
Thankyou, we have now worked out the issues we were having and have managed to get it working.
