### ISSUE TITLE
App behaviour: Fulfillment Services Manager vs Fulfillment Services Operator

### ISSUE THREAD

**Issue by UNSWDigitalLibrary** [ExLibrisGroup/Cloud-App-Change-RS-Requests#4]
[Change RS request type app – Article to Book - Fulfillment Services Operator vs Fulfillment Services Manager.docx](https://github.com/ExLibrisGroup/Cloud-App-Change-RS-Requests/files/6233577/Change.RS.request.type.app.Article.to.Book.-.Fulfillment.Services.Operator.vs.Fulfillment.Services.Manager.docx)

Users with Fulfillment Services Operator see different App functionality to those with Fulfillment Services Manager: 

•	Fulfillment Services Operator:
When users with this role use the App, a new request is created and the original request remains in Alma. 
•	Fulfillment Services Manager: 
When users with this role use the App, a new request is created and the original request is deleted. 

Could the app be enhanced to give Alma staff users with Fulfillment Services Manager role the option to NOT delete the original request? Staff have encountered an issue where Journal title is not migrated to the Book form and this data is lost if the user has the role Fulfillment Services Manager (see separate problem report).

**Comment by ori229** [comment]
This is a good idea. We'll consider it and update here soon.

**Comment by UNSWDigitalLibrary** [comment]
Are you able to give us a rough estimate when the Fulfillment Services Manager vs Fulfillment Services Operator change to the app might be worked on?

**Comment by ori229** [comment]
...very soon.
We'll add a new checkbox to the Settings page (default's to true):
![image](https://user-images.githubusercontent.com/139582/119867595-ba49e700-bf26-11eb-8123-373d2de31b03.png)
