### ISSUE TITLE
Article form to Book form -  Journal title is not migrated  

### ISSUE THREAD

**Issue by UNSWDigitalLibrary** [ExLibrisGroup/Cloud-App-Change-RS-Requests#5]
When we use the “change RS request type” app citation the Journal Tilte frield from the original Article form is NOT imported into the Book form

Could app settings be altered / created for either option below:

•	Article/Chapter title -> Chapter Number field (instead of Title field)   and
Journal title -> to Title field 

or

•	Both Journal title and Article/Chapter title -> Title field, separated by ‘,’ (like Volume and Issue field content)

If the user has the Fulfillment Services manager role, the Article recird is automatically deleted and the user has no way to access the Journal title data. (see separate report re the roles issue)

[Article form to Book - Journal title field data is not migrated.docx](https://github.com/ExLibrisGroup/Cloud-App-Change-RS-Requests/files/6233613/Article.form.to.Book.-.Journal.title.field.data.is.not.migrated.docx)

**Comment by UNSWDigitalLibrary** [comment]
Ideally we would like:

- Journal title to be migrated to the Book title field
- Article title to the Chapter number field (this we use instead of the chapter title field), 

If this is not possible then Journal title/article title option in the Book title field is fine and we can move the chapter title to the relevant field.

Thanks

**Comment by ori229** [comment]
I'll take your 2nd suggestion ("Journal title/article title option in the Book title field"):
Before I commit - how does that look? (the new line is unchecked by default):
![image](https://user-images.githubusercontent.com/139582/117138981-60854f80-adb4-11eb-8299-8194d63801ed.png)

**Comment by UNSWDigitalLibrary** [comment]
Hi

Yes that will be OK. Staff can transfer the data to the correct field after the change.

**Comment by ori229** [comment]
Fixed (new version of the App was Released a few minutes ago - v0.0.8)
