### ISSUE TITLE
"Delete old requests..." checkbox doesn't appear to work

### ISSUE THREAD

**Issue by tmo222** [ExLibrisGroup/Cloud-App-Change-RS-Requests#8]
We have the "Delete old requests after creating the new one" checkbox checked, but old requests aren't being deleted after the new requests are created.  The staff member testing this Cloud App had both the Fulfillment Services Operator and Fulfillment Services Manger roles for the scope she's working in.

**Comment by ori229** [comment]
Can you check if the App's setting has "Delete old requests after creating the new one"?
Is there any error message?
Thanks,
Ori
p.s. What is your institution's code?

**Comment by tmo222** [comment]
Yes, the "Delete old requests..." setting is checked.
My colleague who tested it didn't mention an error message.
Our institution code is 01USGSL

Thanks, Ori.  Sorry it took so long to get back to you

Tami Morse
USGS Libraries
