### ISSUE TITLE
Article to Book form - Additional field suggestions

### ISSUE THREAD

**Issue by EmeliaS** [ExLibrisGroup/Cloud-App-Change-RS-Requests#9]
Hi,

Within the settings for converting an article form to a book form could an option for sending the Article\Chapter title -> Chapter title be added?
Currently you can only choose to send it to the title field. But if you already have the Journal title  going to the Title field then that title information seems to override the chapter information (rather than append it).

Also can we add an option for the DOI -> Other standard ID so we can capture that information.

Thanks,
Emelia

**Comment by EmeliaS** [comment]
> @EmeliaS , We added Support for both in a new Release today. Can you please verify it works as you expected?

When I looked there is an additional field in the settings, however it is sitting under the Book to Article form, not the Article to Book form.

I couldn't see an option for the DOI either. I've attached a screenshot of what i see.
![image](https://user-images.githubusercontent.com/84109001/176069092-f6cf13e3-6d98-4641-b30e-a7719995d3b0.png)

**Comment by ori229** [comment]
@EmeliaS , may I ask you to try and "Reset" the settings?

**Comment by EmeliaS** [comment]
@ori229 That worked, they appeared! 
Thanks for your help.
Emelia
